#plugin must be referenced with full name from collection
plugin: azure.azcollection.azure_rm
auth_source: credential_file
# plain_host_names: yes
# our resource group
include_vm_resource_groups:
- itisfine-terraform

conditional_groups:
  domain_controller: "tags.role == 'domain-controller'"
  workstations: "tags.role == 'workstation'"
  logger: "tags.role == 'logger'"
  collector: "tags.role == 'wef'"
keyed_groups:
- prefix: tag
  key: tags

