---
- name: Join computer to domain
  hosts: workstations
  gather_facts: no
  vars:
    domain_name: ncisg.lab
    domain_admin: domadmin
    domain_admin_password: "Ncisglab123."
    safe_mode_password: "Thisisthe000safepassword!!!"

  tasks: 
  - name: Set DC as DNS server
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses: "{{ hostvars[groups['domain_controller'][0]].private_ipv4_addresses }}" # Get IP address from dynamic inventory

  - name: Ensure workstation is domain-joined
    win_domain_membership:
      dns_domain_name: "{{ domain_name }}"
      hostname: "{{ hostvars[groups['workstations'][0]].name }}" #Get name for hostname from VM name in inventory
      domain_admin_user: "{{ domain_admin }}@{{ domain_name }}"
      domain_admin_password: "{{ domain_admin_password }}"
      state: domain
    register: domain_state
  - name: Reboot machine if it has just joined the domain
    win_reboot: 
      pre_reboot_delay: 15
      reboot_timeout: 150
      post_reboot_delay: 30
    when: domain_state.reboot_required